name: SimpleJoinMessages
version: '${project.version}'
main: com.beans.simplejoinmessages.main
api-version: 1.13
depend: [PlaceholderAPI]
authors: [Beans]
description: A simple plugin to Customize your server's Join and Leave Messages
commands:
  sjmreload:
    usage: /<command>
    description: Reloads SimpleJoinMessage Plugin's config file
    permission: sjm.reload